apiVersion: v1
kind: Pod
metadata:
  name: nginx-labels
  labels:
    team: developers
    version: 1.2.3
    environment: development
spec:
  containers:
    - name: nginx-labels
      image: nginx
      ports:
        - containerPort: 80
