apiVersion: v1
kind: Service # Type of the kubernetes resource
metadata:
  name: birth-service # Name of the Kubernetes resource
  labels: # Labels that will be applied to the resource
    app: birth-service
spec:
  type: NodePort # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: birth-service # Selects any Pod with labels `app=fullstack-app-mysql`
  ports:
    - name: http
      port: 8081
      targetPort: 8081
