apiVersion: apps/v1
kind: Deployment # Type of the kubernetes resource
metadata:
  name: married-service # Name of the Kubernetes resource
  labels:
    app: married-service
spec:
  replicas: 2 # Number of pods to run at any given time
  selector:
    matchLabels:
      app: married-service # This deployment applies to any Pods matching the specified label
  template: # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels: # The labels that will be applied to all of the pods in this deployment
        app: married-service
    spec: # Spec for the container which will run in the Pod
      containers:
        - name: married-service
          image: rizalhamdana/married-service:1.0.2 # The image we are getting from dockerhub
          imagePullPolicy: IfNotPresent # If we have not pulled it before, get it from dockerhub
          ports:
            - name: http
              containerPort: 8083 # Should match the port number that the Go application listens on
          envFrom:
            - secretRef:
                name: mongodb-server # Name of the secret environmental variable file to load
