apiVersion: v1
kind: PersistentVolumeClaim # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata: # Claim name and labels
  name: mysql-pv-claim
  labels:
    app: mysql-server
spec: # Access mode and resource limits
  storageClassName: manual # Request a certain storage class
  accessModes:
    - ReadWriteMany # ReadWriteMany means the volume can be mounted as read-write by many Nodes
  resources:
    requests:
      storage: 3Gi
