apiVersion: apps/v1
kind: Deployment # Type of the kubernetes resource
metadata:
  name: mysql-server # Name of the deployment (Use this name as db host in your application)
  labels: # Labels applied to this deployment
    app: mysql-server
spec:
  selector:
    matchLabels: # This deployment applies to the Pods matching the specified labels
      app: mysql-server
      tier: mysql
  strategy:
    type: Recreate
  replicas: 1
  template: # Template for the pods in this deployment
    metadata:
      labels: # labels to be applied to the pods in this deployment
        app: mysql-server
        tier: mysql
    spec: # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: mysql:5.7 # The container image
          name: mysql
          imagePullPolicy: "IfNotPresent" # Get it from dockerhub if it is not present in our machine

          envFrom: # Environment variables passed to the container
            - secretRef: # Read environment variables from kubernetes secrets
                name: mysql-secret

          ports:
            - containerPort: 3306 # The port that the container exposes
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage # This name should match the name specified in `volumes.name`
      volumes: # A PersistentVolume is mounted as a volume to the Pod
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
