apiVersion: v1 # API version
kind: Service # Type of kubernetes resource
metadata:
  name: mysql-server # Name of the resource
  labels: # Labels that will be applied to the resource
    app: mysql-server
spec:
  type: NodePort
  ports:
    - port: 3306
  selector: # Selects any Pod with labels `app=fullstack-mysql,tier=mysql`
    app: mysql-server
    tier: mysql
