apiVersion: v1
kind: Service # Type of the kubernetes resource
metadata:
  name: family-service # Name of the Kubernetes resource
  labels: # Labels that will be applied to the resource
    app: family-service
spec:
  type: NodePort # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: family-service # Selects any Pod with labels `app=fullstack-app-mysql`
  ports:
    - name: family-service
      protocol: TCP
      port: 8082
      targetPort: 8082
