apiVersion: v1
kind: Service # Type of the kubernetes resource
metadata:
  name: admin-service # Name of the Kubernetes resource
  labels: # Labels that will be applied to the resource
    app: admin-service
spec:
  type: NodePort # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: admin-flask-service # Selects any Pod with labels `app=fullstack-app-mysql`
  ports:
    - name: admin-service
      protocol: TCP
      port: 5000
      targetPort: 5000
